# Generated by Django 4.2.6 on 2023-10-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='writer',
        ),
    ]
